spring.datasource.url=jdbc:h2:file:./data/ps_project;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

api.security.token.secret=MinhaChaveSecretaSuperSegura2026!

spring.flyway.baseline-on-migrate=true

logging.level.org.springframework.security=DEBUG

server.port=8082

#Ativando o modo dev para liberar as rotas para acesso de desenvolvimento, sem necessidade de autenticação
spring.profiles.active=dev
